name: 'wgetpaste test runner'
on: [pull_request, push]
jobs:
  run-tests:
    strategy:
      matrix:
        test: [test, test_ansi]
    name: "Run test/${{ matrix.test }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install meson ${{ matrix.test == 'test_ansi' && 'ansifilter' || '' }}
        shell: bash

      - name: 'Build wgetpaste'
        run: |
          mkdir build
          meson setup build --prefix="/"
        shell: bash

      - run: meson test -C ./build ${{ matrix.test }}
