name: 'wgetpaste test runner'
on: [pull_request, push]
jobs:
  run-tests:
    strategy:
      matrix:
        test: [test.sh, test_ansi.sh]
    name: "Run test/${{ matrix.test }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install meson ${{ matrix.test == 'test_ansi.sh' && 'ansifilter' || '' }}
        shell: bash

      - name: 'Build wgetpaste'
        run: |
          mkdir build
          meson setup build --prefix="/"
          meson install -C ./build --destdir="$PWD/build/image"
        shell: bash

      - run: test/${{ matrix.test }}
